# -*- coding: utf-8 -*-
"""Sistem Rekomendasi_FinPro DS.ipynb
Automatically generated by Colab.
"""

# ==========================================
# 1. Import Library
# ==========================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import random
import warnings
warnings.filterwarnings('ignore')

# ==========================================
# 2. Data Collecting & Preprocessing
# ==========================================
# Membaca dataset utama
df = pd.read_csv('netflix_titles.csv')

# Mengisi Missing Value
df['director'] = df['director'].fillna('')
df['cast'] = df['cast'].fillna('')
df['country'] = df['country'].fillna('')
df['description'] = df['description'].fillna('')
df['listed_in'] = df['listed_in'].fillna('')

# Menghapus Data Duplikat
df.drop_duplicates(inplace=True)

# Fungsi membersihkan text
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\n', '', text)
    text = re.sub(r'\w*\d\w*', '', text)
    return text

# Membersihkan Kolom Description
df['clean_description'] = df['description'].apply(clean_text)

# Menggabungkan fitur penting menjadi satu text gabungan
df['combined_features'] = (
    df['clean_description'] + ' ' +
    df['listed_in'] + ' ' +
    df['cast'] + ' ' +
    df['director']
)

# ==========================================
# 3. Model Training
# ==========================================
# TF-IDF Vectorization
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['combined_features'])

# Cosine Similarity
cosine_sim = cosine_similarity(tfidf_matrix)

# Membuat Index Film
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

# ==========================================
# 4. Fungsi Rekomendasi (Backend)
# ==========================================
# Rekomendasi berdasarkan judul film
def recommend_movies(title):
    if title not in indices:
        return "Movie not found in dataset"
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return df[['title', 'listed_in']].iloc[movie_indices]

# Pemetaan Mood Keywords
mood_keywords = {
    "Happy": "comedy family",
    "Sad": "drama emotional",
    "Excited": "action thriller",
    "Romantic": "romance love",
    "Sci-Fi": "science fiction space",
    "Chill": "documentary drama"
}

# Rekomendasi berdasarkan kategori mood
def recommend_by_mood(mood):
    keywords = mood_keywords[mood]
    user_vector = tfidf.transform([keywords])
    similarity = cosine_similarity(user_vector, tfidf_matrix)
    similarity_scores = list(enumerate(similarity[0]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    top_movies_list = similarity_scores[:10]
    movie_indices = [i[0] for i in top_movies_list]
    return df[['title', 'listed_in', 'description']].iloc[movie_indices]

# Random Movie Picker
def random_movie():
    random_pick = df.sample(1)
    return random_pick[['title', 'listed_in', 'description']]

# Movie of The Day
movie_of_the_day = df.sample(1)

# ==========================================
# 5. Model Evaluation (Terminal Logs)
# ==========================================
# Perbaikan variabel evaluasi agar tidak memicu NameError
try:
    selected_mood = 'Happy'
    keywords = mood_keywords[selected_mood]
    user_vector = tfidf.transform([keywords])
    similarity = cosine_similarity(user_vector, tfidf_matrix)
    similarity_scores = list(enumerate(similarity[0]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    eval_top_movies = similarity_scores[:10]

    print("--- RUNNING EVALUATION ---")
    for i in eval_top_movies:
        movie_index = i[0]
        score = i[1]
        print("Title:", df.iloc[movie_index]['title'])
        print("Similarity Score:", round(score, 3))
        print("-" * 40)
except Exception as e:
    print("Evaluation log error:", e)

# ==========================================
# 6. ANTARMUKA USER (STREAMLIT UI)
# ==========================================
import streamlit as st

st.title("🎬 MovRec: Sistem Rekomendasi Film Netflix")
st.write("Selamat datang! Temukan film terbaik berdasarkan mood atau dapatkan rekomendasi acak hari ini.")

# Menu Navigasi di Sidebar
menu = st.sidebar.selectbox("Pilih Fitur", ["Rekomendasi Berdasarkan Mood", "Cari Film Mirip", "Movie of The Day & Random"])

if menu == "Rekomendasi Berdasarkan Mood":
    st.subheader("🎭 Cari Film Sesuai Mood Kamu")
    pilihan_mood = st.selectbox("Bagaimana perasaanmu hari ini?", list(mood_keywords.keys()))
    
    if st.button("Cari Rekomendasi"):
        hasil_mood = recommend_by_mood(pilihan_mood)
        for index, row in hasil_mood.iterrows():
            st.write(f"### 🍿 {row['title']}")
            st.caption(f"**Genre:** {row['listed_in']}")
            st.write(row['description'])
            st.write("---")

elif menu == "Cari Film Mirip":
    st.subheader("🔍 Cari Film yang Mirip dengan Film Favoritmu")
    judul_input = st.text_input("Ketikkan Judul Film Netflix (Contoh: 9, Transformers, dll):")
    
    if st.button("Cari Kembaran Film"):
        if judul_input:
            hasil_mirip = recommend_movies(judul_input)
            if isinstance(hasil_mirip, str):
                st.warning(hasil_mirip)
            else:
                st.dataframe(hasil_mirip)
        else:
            st.error("Silakan ketik judul film terlebih dahulu!")

elif menu == "Movie of The Day & Random":
    st.subheader("📅 Movie of The Day")
    if st.button("Tampilkan Movie of The Day"):
        motd = movie_of_the_day
        st.info(f"### 🌟 {motd['title'].values[0]}")
        st.write(motd['description'].values[0])
        
    st.write("---")
    st.subheader("🎲 Random Movie Picker")
    if st.button("Pilihkan Film Acak secara Random"):
        acak = random_movie()
        st.success(f"### 🎬 {acak['title'].values[0]}")
        st.caption(f"**Genre:** {acak['listed_in'].values[0]}")
        st.write(acak['description'].values[0]) 
